# Generated by Django 6.0.3 on 2026-03-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('computer_tag', models.CharField(blank=True, max_length=100)),
                ('display_tag', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('work_order', models.CharField(blank=True, max_length=100)),
                ('inventory_receipt', models.CharField(blank=True, max_length=100)),
                ('inventory_issuance', models.CharField(blank=True, max_length=100)),
                ('po', models.CharField(blank=True, max_length=100, verbose_name='PO')),
                ('remarks', models.TextField(blank=True)),
                ('assigned_person', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Repair', 'Under Repair'), ('Disposed', 'Disposed'), ('For Repair', 'For Repair')], default='Active', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Security', 'Security'), ('Network Devices', 'Network Devices'), ('Electrical Devices', 'Electrical Devices'), ('Tools', 'Tools'), ('Telephony', 'Telephony'), ('Display', 'Display')], max_length=50)),
                ('classification', models.CharField(choices=[('Components', 'Components'), ('Parts', 'Parts')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
